name: Release Tools
on: ["push"]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust toolchain on macOS
      if: startsWith(matrix.os, 'macos')
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.RUST_VERSION }}
        profile: minimal
        override: true
        components: clippy
    - name: Update
      uses: actions-rs/cargo@v1
      with:
        command: update
    - name: collect artifact on Linux
      run: |
        rustup component add rustfmt
        cd pahkat-client-core
        cargo build  --features ffi,prefix
    